[project]
name = "project-tcc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.16.0",
    "icecream>=2.1.8",
    "ipykernel>=7.0.1",
    "litellm>=1.78.3",
    "pylint>=4.0.1",
    "pytest>=9.0.0",
    "pytest-asyncio>=1.3.0",
    "sqlmodel>=0.0.27",
    "yfinance>=0.2.66",
]
